move_to_spot:
  ros__parameters:
    corner1:
      position:
        x: 1.2
        y: 2.3
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.707
        w: 0.707

    corner2:
      position:
        x: -0.5
        y: 3.1
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.5
        w: 0.866

    pedestrian:
      position:
        x: 2.5
        y: -1.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.707
        w: 0.707
